FROM node:22-slim@sha256:5373f1906319b3a1f291da5d102f4ce5c77ccbe29eb637f072b6c7b70443fc36

WORKDIR /app

# hadolint ignore=DL3008
RUN apt-get update && apt-get install --no-install-recommends -y \
  git \
  ca-certificates \
  wget \
  bash \
  procps \
  && rm -rf /var/lib/apt/lists/*

RUN git config --global --add safe.directory "*"

ENV NODE_ENV=serverest-test

COPY package*.json ./

RUN npm ci

COPY . .
